In [1]:
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import numpy as np
import os
import astropy.units as u
import h5py

from read_simulation_data.get_mpi_info import get_mpi_info

DATA_FOLDER = "/mn/stornext/d10/data/tabjone/data/"
R_SUN = 6.957e10

In [11]:
# Directory containing the snapshot files
directory = DATA_FOLDER + 'test_other_ic_4'
num = 0
# Iterate over all files in the directory
for filename in os.listdir(directory):
    if filename.startswith("snap") and filename.endswith(".h5"):
        # Split the filename to extract the snapshot number
        parts = filename.split('p')
        parts = parts[1].split('.')
        parts = parts[0].split('_')
        snap_number = int(parts[0])
        if snap_number > 3040:
            # Construct full file path
            file_path = os.path.join(directory, filename)
            # Delete the file
            os.remove(file_path)

In [3]:
SAVE_FOLDER = 'data/'
RUN_NAME = "mpi_test/"

In [51]:
def get_background_variable(folder, variable_key):
    # Get the number of processes
    num_processes = get_mpi_info(folder+'mpi_info.h5')

    # Variable from all processes
    variable = []

    for i in range(num_processes):
        with h5py.File(f'{folder}background_{i}.h5', 'r') as f:
            dataset = f[f'variables/{variable_key}']
            process_variable = np.array(dataset)
            unit_attr = dataset.attrs['unit']
            unit = unit_attr[0].decode('utf-8') if isinstance(unit_attr[0], bytes) else unit_attr[0]
            nz_ghost = np.array(f['grid_info/nz_ghost'])

            if num_processes ==1:
                variable.append(process_variable)
            else:
                if i == 0:
                    variable.append(process_variable)
                elif i == num_processes - 1:
                    variable.append(process_variable)
                else:
                    variable.append(process_variable)
    
    # Concatenating the data for each variable
    #variable = np.concatenate(variable, axis=0)

    return variable, unit

def get_foreground_variable(folder, snap_number, variable_key):
    # Get the number of processes
    num_processes = get_mpi_info(folder+'mpi_info.h5')

    # Variable from all processes
    variable = []

    for i in range(num_processes):
        with h5py.File(f'{folder}snap{snap_number}_{i}.h5', 'r') as f:
            t = np.array(f['grid_info/t'])
            dataset = f[f'variables/{variable_key}']

            unit_attr = dataset.attrs['unit']
            unit = unit_attr[0].decode('utf-8') if isinstance(unit_attr[0], bytes) else unit_attr[0]

            process_variable = np.array(dataset)
            nz_ghost = np.array(f['grid_info/nz_ghost'])

            if num_processes ==1:
                variable.append(process_variable)
            else:
                if i == 0:
                    variable.append(process_variable)
                elif i == num_processes - 1:
                    variable.append(process_variable)
                else:
                    variable.append(process_variable)
    
    # Concatenating the data for each variable
    #variable = np.concatenate(variable, axis=0)
    
    return variable, unit, t

In [59]:
s1 = get_foreground_variable(DATA_FOLDER+RUN_NAME, 0, 'p1')[0]

In [60]:
s1[0][:,:3]

array([[       0.        ,        0.        ,        0.        ],
       [       0.        ,        0.        ,        0.        ],
       [      -0.        , 44375026.562393  , 88571370.55470836],
       [      -0.        , 42327690.02317098, 84484941.37791309],
       [      -0.        , 40179023.86723116, 80196260.98628509],
       [      -0.        , 37945109.70034231, 75737427.83641134],
       [      -0.        , 35640102.08659754, 71136694.0610443 ],
       [      -0.        , 33279515.20749402, 66425025.55304497],
       [      -0.        , 30876957.15124941, 61629583.69388037],
       [      -0.        , 28447100.00225411, 56779653.57302583],
       [      -0.        , 26002765.51265519, 51900827.06610499],
       [      -0.        , 23557546.18931408, 47020234.45461293],
       [      -0.        , 21123272.3182492 , 42161488.67420016],
       [      -0.        , 18712259.10587052, 37349170.54869695],
       [      -0.        , 16335177.02528467, 32604578.05808745],
       [  

In [61]:
s1[1][:,:3]

array([[       -0.        ,   3325468.23117019,   6637545.97547676],
       [       -0.        ,   1439327.7386179 ,   2872859.81243415],
       [       -0.        ,   -349854.23612012,   -698299.73271025],
       [       -0.        ,  -2037668.12221216,  -4067131.27407843],
       [       -0.        ,  -3620450.37229927,  -7226322.46876469],
       [       -0.        ,  -5095398.9755893 , -10170280.57789321],
       [       -0.        ,  -6460244.64282971, -12894476.16058584],
       [       -0.        ,  -7713719.9147338 , -15396379.40188034],
       [       -0.        ,  -8854875.32885422, -17674095.20003221],
       [       -0.        ,  -9883876.76536227, -19727954.64744315],
       [       -0.        , -10800995.92538143, -21558500.05231556],
       [       -0.        , -11607706.87118015, -23168673.60365787],
       [       -0.        , -12305383.59258651, -24561217.74855414],
       [       -0.        , -12896663.75553787, -25741397.1979293 ],
       [       -0.        , -13383

In [62]:
s1[2][:,:3]

array([[       -0.        , -14333491.82355575, -28609267.73445465],
       [       -0.        , -14204211.31362309, -28351227.28157409],
       [       -0.        , -14005777.32437361, -27955158.32671381],
       [       -0.        , -13744122.96756783, -27432903.20284782],
       [       -0.        , -13424144.19185034, -26794234.09300814],
       [       -0.        , -13051920.35705446, -26051285.23742502],
       [       -0.        , -12632406.49737375, -25213946.75231173],
       [       -0.        , -12171673.07605292, -24294335.12054475],
       [       -0.        , -11674601.78460233, -23302194.06829602],
       [       -0.        , -11147112.34933596, -22249339.21154498],
       [       -0.        , -10593894.22550565, -21145130.57801414],
       [       -0.        , -10020590.24206305, -20000831.10392619],
       [       -0.        ,  -9431594.30053145, -18825210.89963709],
       [       -0.        ,  -8832163.67182751, -17628763.33780571],
       [       -0.        ,  -8226